baseURL = "https://wisec26.scy-phy.net/"

languageCode = "en-us"
title = "ACM WiSec 2026"

## TO DO
Copyright = "ACM"
theme = "conference"
disableKinds = ["taxonomy"]
enableGitInfo = false


[markup.goldmark.renderer]
	unsafe = true

[params]
	banner_title = "<b>19<sup>th</sup> ACM Conference on Security and Privacy in Wireless and Mobile Networks</b>"
	banner_subtitle = "<b>Saarbrücken, Germany<br>June 30 - July 3, 2026</b>"
	banner_images = [ "images/saarschleife.png", "images/sb2.jpg", "images/hotel.png"]

	banner_width = "1200px"
	toc_heading = "Table of Contents"
	toc_heading_show = false
	toc_show = false

[[menu.main]]
    name = "Program"
    identifier = "menu_program"
##    url = "/program-at-a-glance/"
    weight = 2000

##[[menu.main]]
##  name = "Proceedings"
##  identifier = "wisec-proceedings"
##  parent = "menu_program"
##  url = "https://wisec26.scy-phy.net/proceedings/acm-wisec-2026-toc.html"
##  weight = 6000

##[[menu.main]]
##    name = "Call for"
##    url = "/call-for-papers/"
##    weight = 3000

  [[menu.main]]
  name = "wiseml2026"
  title = "WiseML 2026"
  weight = 4000
##  url = "/wiseml2026-workshops/"

##  [[menu.main]]
##    name = "Proceedings"
##    identifier = "wiseml-proceedings"
##    parent = "wiseml2026"
##    url = "https://wisec26.scy-phy.net/proceedings/acm-wiseml-2026-toc.html"
##    weight = 4000

##  [[menu.main]]
##  name = "Organization"
##  identifier = "Organization"
##  url = "/organization-committee/"
##  weight = 6000

##  [[menu.main]]
##  name = "Attending"
##  title = "Attending"
##  weight = 7000
##  url = "/attending-registration/"

#[[menu.sociallinks]]
#	name = "Twitter @acm_wisec"
#	pre = "fab fa-twitter"
#	url = "https://twitter.com/acm_wisec"
#    weight = 1

#a[[menu.sociallinks]]
#	name = "YouTube"
#	pre = "fab fa-youtube"
#	url = "https://www.youtube.com/channel/UCuoCDm4vGr7t7MdD3zt3P3g"
#    weight = 2

# [[menu.main]]
#     name = "Travel"
# 	identifier = "travel_info"
#     url = "/student-travel-grants/"
#     weight = 11011